[project]
name = "segmenteer"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "cucim-cu13>=26.2.1",
    "geojson>=3.2.0",
    "imagecodecs>=2025.3.30",
    "monai[cucim,openslide]",
    "numpy>=2.2.6",
    "opencv-python>=4.13.0.90",
    "pillow>=12.1.0",
    "pyvips>=3.1.1.8.18.0",
    "scikit-image>=0.25.2",
    "scikit-learn>=1.7.2",
    "scipy>=1.15.3",
    "shapely>=2.1.2",
    "tifffile>=2025.5.10",
    "tissue-segmentation",
    "trident",
    "wsidicom>=0.29.0",
]

[project.optional-dependencies]
dev = [
    "matplotlib>=3.10.8",
    "pytest>=9.0.2",
]
entropymasker = [
    "dask>=2024.10.0",
]
cpg = [
    "docker>=7.1.0",
]
openslide = [
    "openslide-bin>=4.0.0.11",
    "openslide-python>=1.4.3.1",
]
dl = [
    "huggingface-hub>=0.36.0",
    "segmentation-models-pytorch>=0.5.0",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "transformers>=4.57.6",
    "ultralytics>=8.4.6",
]
fastsam = [
    "openai-clip>=1.0.1",
    "ultralytics>=8.4.6",
]
histomicstk = [
    "histomicstk>=1.4.0",
]
slidesegmenter = [
    "slidesegmenter",
]

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[[tool.uv.index]]
name = "large_image"
url = "https://girder.github.io/large_image_wheels"

[tool.uv.build-backend]
module-root = ""
module-name = "segmenteer"

[tool.uv.sources]
large_image  = { index = "large_image"}
monai = { git = "https://github.com/NikolasSchmitz/MONAI", rev = "ece78c46ae263a2e24c9d1bc1d97f95e50eae2f4" }
slidesegmenter = { git = "https://github.com/RTLucassen/slidesegmenter", rev = "9d9d690913d6e8520a24d678f54decccd59dce9e" }
trident = { git = "https://github.com/mahmoodlab/trident.git", rev = "adf3b7e8fdd7c815f33bec79da0d8d265200c2d6"}
tissue-segmentation = { git = "https://github.com/imi-bigpicture/tissue-segmentation.git", subdirectory = "tissue_segmentation", rev = "6d97a25a8255f591eb2c705611a32a5f56101a25"}

[tool.uv]
index-strategy = "unsafe-best-match"
